//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFChatClient.ChatService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChatService.IChat")]
    public interface IChat {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/SubmitUserMessage", ReplyAction="http://tempuri.org/IChat/SubmitUserMessageResponse")]
        void SubmitUserMessage(WCFChatService.UserMessage post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/SubmitUserMessage", ReplyAction="http://tempuri.org/IChat/SubmitUserMessageResponse")]
        System.Threading.Tasks.Task SubmitUserMessageAsync(WCFChatService.UserMessage post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/GetChats", ReplyAction="http://tempuri.org/IChat/GetChatsResponse")]
        WCFChatService.UserMessage[] GetChats();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/GetChats", ReplyAction="http://tempuri.org/IChat/GetChatsResponse")]
        System.Threading.Tasks.Task<WCFChatService.UserMessage[]> GetChatsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/RemoveChatt", ReplyAction="http://tempuri.org/IChat/RemoveChattResponse")]
        void RemoveChatt(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/RemoveChatt", ReplyAction="http://tempuri.org/IChat/RemoveChattResponse")]
        System.Threading.Tasks.Task RemoveChattAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/SaveToDatabase", ReplyAction="http://tempuri.org/IChat/SaveToDatabaseResponse")]
        void SaveToDatabase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/SaveToDatabase", ReplyAction="http://tempuri.org/IChat/SaveToDatabaseResponse")]
        System.Threading.Tasks.Task SaveToDatabaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/GetChatFromDatabase", ReplyAction="http://tempuri.org/IChat/GetChatFromDatabaseResponse")]
        WCFChatService.UserMessage[] GetChatFromDatabase(int roomID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/GetChatFromDatabase", ReplyAction="http://tempuri.org/IChat/GetChatFromDatabaseResponse")]
        System.Threading.Tasks.Task<WCFChatService.UserMessage[]> GetChatFromDatabaseAsync(int roomID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/RegisterUser", ReplyAction="http://tempuri.org/IChat/RegisterUserResponse")]
        void RegisterUser(WCFChatService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/RegisterUser", ReplyAction="http://tempuri.org/IChat/RegisterUserResponse")]
        System.Threading.Tasks.Task RegisterUserAsync(WCFChatService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/LogInUser", ReplyAction="http://tempuri.org/IChat/LogInUserResponse")]
        WCFChatService.User LogInUser(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/LogInUser", ReplyAction="http://tempuri.org/IChat/LogInUserResponse")]
        System.Threading.Tasks.Task<WCFChatService.User> LogInUserAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/LogOutUser", ReplyAction="http://tempuri.org/IChat/LogOutUserResponse")]
        void LogOutUser(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/LogOutUser", ReplyAction="http://tempuri.org/IChat/LogOutUserResponse")]
        System.Threading.Tasks.Task LogOutUserAsync(string userName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatChannel : WCFChatClient.ChatService.IChat, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatClient : System.ServiceModel.ClientBase<WCFChatClient.ChatService.IChat>, WCFChatClient.ChatService.IChat {
        
        public ChatClient() {
        }
        
        public ChatClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChatClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SubmitUserMessage(WCFChatService.UserMessage post) {
            base.Channel.SubmitUserMessage(post);
        }
        
        public System.Threading.Tasks.Task SubmitUserMessageAsync(WCFChatService.UserMessage post) {
            return base.Channel.SubmitUserMessageAsync(post);
        }
        
        public WCFChatService.UserMessage[] GetChats() {
            return base.Channel.GetChats();
        }
        
        public System.Threading.Tasks.Task<WCFChatService.UserMessage[]> GetChatsAsync() {
            return base.Channel.GetChatsAsync();
        }
        
        public void RemoveChatt(int id) {
            base.Channel.RemoveChatt(id);
        }
        
        public System.Threading.Tasks.Task RemoveChattAsync(int id) {
            return base.Channel.RemoveChattAsync(id);
        }
        
        public void SaveToDatabase() {
            base.Channel.SaveToDatabase();
        }
        
        public System.Threading.Tasks.Task SaveToDatabaseAsync() {
            return base.Channel.SaveToDatabaseAsync();
        }
        
        public WCFChatService.UserMessage[] GetChatFromDatabase(int roomID) {
            return base.Channel.GetChatFromDatabase(roomID);
        }
        
        public System.Threading.Tasks.Task<WCFChatService.UserMessage[]> GetChatFromDatabaseAsync(int roomID) {
            return base.Channel.GetChatFromDatabaseAsync(roomID);
        }
        
        public void RegisterUser(WCFChatService.User user) {
            base.Channel.RegisterUser(user);
        }
        
        public System.Threading.Tasks.Task RegisterUserAsync(WCFChatService.User user) {
            return base.Channel.RegisterUserAsync(user);
        }
        
        public WCFChatService.User LogInUser(string userName, string password) {
            return base.Channel.LogInUser(userName, password);
        }
        
        public System.Threading.Tasks.Task<WCFChatService.User> LogInUserAsync(string userName, string password) {
            return base.Channel.LogInUserAsync(userName, password);
        }
        
        public void LogOutUser(string userName) {
            base.Channel.LogOutUser(userName);
        }
        
        public System.Threading.Tasks.Task LogOutUserAsync(string userName) {
            return base.Channel.LogOutUserAsync(userName);
        }
    }
}
